### ISSUE TITLE
Bytes / Array data type does not convert correctly

### ISSUE THREAD

**Issue by lcr95** [benwatson528/intellij-avro-plugin#3]
Seem like the plugin having issue when dealing with "bytes" and "array" data type. 

This is my schema 
![image](https://user-images.githubusercontent.com/11770243/57747895-07750a80-770a-11e9-89c4-930c93a55695.png)

Result form avro viewer :
![image](https://user-images.githubusercontent.com/11770243/57747937-3ee3b700-770a-11e9-82d3-0092de910cbf.png)

Expected :
![image](https://user-images.githubusercontent.com/11770243/57747971-65a1ed80-770a-11e9-8a55-781f5cd3ba1c.png)

**Comment by benwatson528** [comment]
Hello,

`[3000, 2000, 5000]` is an `array[int]` and not an `array[bytes]`. You should change the type in your schema from `bytes` to `int`.

Thanks,

Ben
