### ISSUE TITLE
Not compatible with IntelliJ IDEA 2019.2 

### ISSUE THREAD

**Issue by arranbartish** [benwatson528/intellij-avro-plugin#4]
It seems like the avro plugin is not compatible any more with the latest iteration of Intellij.

IDE version details below
```
IntelliJ IDEA 2019.2 (Ultimate Edition)
Build #IU-192.5728.98, built on July 23, 2019
Licensed to ME
You have a perpetual fallback license for this version
Subscription is active until August 14, 2020
Runtime version: 11.0.3+12-b304.10 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-29-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 1109M
Cores: 2
Registry: git.explicit.commit.renames.prohibit.multiple.calls=false
Non-Bundled Plugins: PlantUML integration, com.alayouni.ansiHighlight, com.github.redfoos.logstash-intellij-plugin, com.intellij.ideolog, com.microsoft.vso.idea, google-java-format, net.seesharpsoft.intellij.plugins.csv, org.jetbrains.plugins.hocon, BashSupport, com.cybrosis.catdea, com.jetbrains.php, com.vladsch.idea.multimarkdown
```

**Comment by benwatson528** [comment]
Thanks @arranbartish, I normally get an automated email telling me whether or not it's compatible with the latest version of IntelliJ, not sure why I didn't this time but I'll get right onto fixing it.

**Comment by benwatson528** [comment]
@arranbartish I'm still not entirely sure why it failed previous checks, but I've updated the IntelliJ plugin version and it should be re-available in a day or two, following IntelliJ's manual moderation process. I'll keep an eye out and ping you when it's sorted.

**Comment by benwatson528** [comment]
@arranbartish I can confirm it's now working again and available to install through IntelliJ.
