### ISSUE TITLE
Can't read serialized scala.collection.mutable.HashMap

### ISSUE THREAD

**Issue by dteller** [benwatson528/intellij-avro-plugin#6]
Some .avro files work just fine with the plugin.
But I have one that doesn't display any tables and gives me this output in the IntelliJ log:

2019-11-18 09:47:38,492 [  28282]   INFO - llij.avro.AvroViewerToolWindow - Received file /home/dteller/Code/javasrc-gbeskales/connect/job/components/src/test/resources/data/modelEnsemble/modelData.avro 
2019-11-18 09:47:38,680 [  28470]   INFO - thome.intellij.avro.AvroReader - Retrieved 11 records 
2019-11-18 09:47:38,732 [  28522]   INFO - e.intellij.avro.TableFormatter - Found 15 unique columns 
2019-11-18 09:47:45,524 [  35314]   WARN - com.intellij.util.xmlb.Binding - no accessors for class scala.collection.mutable.HashMap 
2

I'm assuming that one of the columns has a serialized HashMap and that is causing the problem.
I tried symlinking the scala jars in the plugins lib folder so it could find the class but that did nothing.

Any suggestions on how to get this to work?

Thanks

Dave

**Comment by benwatson528** [comment]
Hi Dave,

Do you have a sample file so that I can debug into it?

Thanks,

Ben

**Comment by dteller** [comment]
[modelData.zip](https://github.com/benwatson528/intellij-avro-plugin/files/3860040/modelData.zip)
Here you go.

And the command line tools will unpack it. So I really don't understand what is going on here.

Thanks

Dave

**Comment by benwatson528** [comment]
I'll get back to you by the end of Sunday, in the meantime feel free to have a play; all the Avro serde operations are contained within https://github.com/benwatson528/intellij-avro-plugin/blob/master/src/main/java/uk/co/hadoopathome/intellij/avro/AvroReader.java

**Comment by benwatson528** [comment]
I'm not having much luck with this - clearly some Scala jar should be placed somewhere, and I agree that the plugins lib folder seems like the best place. I'd like a generic solution rather than just forcing Scala into my plugin, because pepole could have Avro objects generated from a variety of sources. Will keep trying.

**Comment by dteller** [comment]
I certainly agree with you on that. I tried putting the scala library jars
in the plugins lib folder and that didn't help. I don't know if there is
some other way to add things to the plugin classpath.
That might be a more generic solution.

**Comment by dteller** [comment]
I was in training all last week but I'll see if I can dig into this more
tomorrow.

Thanks for looking at it.

Dave

**Comment by benwatson528** [comment]
I've asked on https://intellij-support.jetbrains.com/hc/en-us/community/posts/360006731700-Adding-external-jars-to-a-plugin-s-classpath

**Comment by dteller** [comment]
Dear Ben -

I've put in a pull request that I think partially solves the problem.
No matter what I did with the dependencies I'm still getting that warning
about the HashMap.
But at least this way it doesn't explode when it gets an empty array.

Thanks

Dave Teller

**Comment by benwatson528** [comment]
Merged and submitted to IntelliJ marketplace, so will be live by the end of the week. In the meantime I'll keep looking if I have time, but no reply from the forum yet so I'm not too hopeful.

Thanks for helping out and contributing!

Ben

**Comment by benwatson528** [comment]
Merged and submitted to IntelliJ marketplace, so will be live by the end of the week. In the meantime I'll keep looking if I have time, but no reply from the forum yet so I'm not too hopeful.

Thanks Dave for helping out and contributing!

Ben

**Comment by dteller** [comment]
I think that serialization error might be unrelated. It doesn't show up in
the logs with the updated plugin.
(At least not for me.)
I actually set a breakpoint in the logger and it never tripped.

But I will dig into it some more and try to see where it is coming from.

**Comment by benwatson528** [comment]
![image](https://user-images.githubusercontent.com/6214761/73197004-84290700-4128-11ea-8782-d8a56ed2f473.png)

I can read this file in the latest version of the plugin without any issues. The schema doesn't say there are any HashMaps inside. Which field inside that file is a HashMap? I've got a bit more time to look at this now.

**Comment by dteller** [comment]
I don't think there actually were any hashmaps in there. I think the actual
problem was an empty List, which I fixed.
I think the HashMap error is something in IntelliJ and not actually related
to the plugin.

**Comment by benwatson528** [comment]
Cool will close this.
